package ejobIndia;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class PracticeTest10 {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		
		// Exercise
		// Launch Chrome Browser
		// Open URL “http://toolsqa.wpengine.com/automation-practice-switch-windows/”
		// Click on Button “Alert Box”, it will open a Pop Up Window generated by JavaScript
		// Switch to Alert window (Use ‘SwitchTo()Alert() command)
		// Close the Pop Up Window (Use Accept command)
		
		WebDriver driver;
		
		String Url = "http://toolsqa.wpengine.com/automation-practice-switch-windows/";
		
		System.setProperty("webdriver.chrome.driver", "D:\\Drivers\\chromedriver.exe");
		driver = new ChromeDriver();
		
				
		//Add Implicit wait
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		//Launch the Url
		driver.get(Url);
		driver.manage().window().maximize();
		
		//Scroll down
		JavascriptExecutor jse = (JavascriptExecutor) driver;
		jse.executeScript("window.scrollBy(0,450)", "");
		
		// Click on the Button "Alert Box"
		driver.findElement(By.id("alert")).click();
		Thread.sleep(2000);
		
		 // Switch to JavaScript Alert window
		Alert alert = driver.switchTo().alert();
		
		// Accept the Alert
		alert.accept();
		System.out.println("Alert accepted");
		Thread.sleep(2000);
		
		// Close Browser
		driver.close();
		System.out.println("Browser Closed");
		

	}

}
